apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gatewayapi
  name: gatewayapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gatewayapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: gatewayapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.application.gatewayapiPort }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value:  {{ .Values.application.otelExporterOtlpEndpoint }}
            - name: locationsapi_ENDPOINT
              value: {{ .Values.application.locationsapiEndpoint }}
            - name: weathersapi_ENDPOINT
              value: {{ .Values.application.weathersapiEndpoint }}
          image: {{ .Values.image.gatewayapiImage }}
          name: gatewayapi
          ports:
            - containerPort: {{ .Values.application.gatewayapiPort }}
          resources: {}
      restartPolicy: Always
status: {}
