apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gatewayapi
  name: gatewayapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.application.gatewayapiPort }}
      targetPort: {{ .Values.application.gatewayapiPort }}
  selector:
    io.kompose.service: gatewayapi
