kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: gatewayapi
  labels:
    io.kompose.service: gatewayapi
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: [host]
      http:
        paths:
          - path: /gatewayapi/(.*)
            pathType: Prefix
            backend:
              service:
                name: gatewayapi
                port:
                  number: 80
