apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: locationsapi
  name: locationsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: locationsapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: locationsapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:5218
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector:4317
          image: locationsapi
          name: locationsapi
          ports:
            - containerPort: 5218
          resources: {}
      restartPolicy: Always
status: {}
