apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: locationsapi
  name: locationsapi
spec:
  ports:
    - name: "5218"
      port: 5218
      targetPort: 5218
  selector:
    io.kompose.service: locationsapi
status:
  loadBalancer: {}
