apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: weathersapi
  name: weathersapi
spec:
  ports:
    - name: "5290"
      port: 5290
      targetPort: 5290
  selector:
    io.kompose.service: weathersapi
status:
  loadBalancer: {}
