apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-all-in-one
  name: zipkin-all-in-one
spec:
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: zipkin-all-in-one
status:
  loadBalancer: {}
