apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-all-in-one
  name: zipkin-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin-all-in-one
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tools\kompose\kompose.exe convert --chart
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: zipkin-all-in-one
    spec:
      containers:
        - image: {{ .Values.image.zipkinImage }}
          name: zipkin-all-in-one
          ports:
            - containerPort: 9411
          resources: {}
      restartPolicy: Always
status: {}
